version: "3.7"
services:
  dynamodb:
    container_name: pocketgems-dynamodb
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-port", "8000"]
  dynamodb-admin:
    container_name: pocketgems-dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://pocketgems-dynamodb:8000
      - AWS_ACCESS_KEY_ID=ignored
      - AWS_SECRET_ACCESS_KEY=ignored
      - AWS_REGION=localhost
networks:
  default:
    name: todea-net
