name: Check PR
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dound'
      - run: yarn install --frozen-lockfile
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Check lint and markdown links'
        run: |
          yarn check-markdown-link
          yarn lint
        shell: bash
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 458.0.0'
          install_components: 'cloud-firestore-emulator'
      - name: 'Run unit tests'
        run: |
          sudo apt-get install -y google-cloud-cli-firestore-emulator
          /scripts/start-local-db.sh > /dev/null 2> /dev/null &
          yarn test
        shell: bash
