name: Check PR
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  check_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dound'
      - run: yarn install --frozen-lockfile
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Check lint and markdown links'
        run: |
          yarn check-markdown-link
          yarn lint
        shell: bash
      - name: 'Setup Firestore Emulator'
        run: |
          echo '{ "projects": { "default": "fake-for-testing-only" } }' > ./.firebaserc
          echo '{ "firestore": {} }' > ./firebase.json
          npm install -g firebase-tools
          firebase setup:emulators:firestore
        shell: bash
      - name: 'Run unit tests'
        run: |
          echo 'yarn test' > ./test.sh
          chmod u+x ./test.sh
          echo "process.env.FIRESTORE_EMULATOR_HOST = 'localhost:8080'" >> ./environment.js
          firebase emulators:exec --only firestore ./test.sh
        shell: bash
