name: Check PR
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dound'
      - run: yarn install --frozen-lockfile
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          yarn check-markdown-link
          yarn lint
          echo '{"firestore": {}}' > ./firebase.json
          echo 'yarn test' > ./test.sh
          chmod u+x ./test.sh
          firebase=./node_modules/firebase-tools/lib/bin/firebase.js
          $firebase setup:emulators:firestore
          $firebase emulators:exec --only firestore ./test.sh
        shell: bash
